In [92]:
import numpy as np
arr1 = np.array([1, 2, 3, 4])
print(arr1)

[1 2 3 4]


In [100]:
arr1+2

array([3, 4, 5, 6])

In [44]:
arr1*2

array([2, 4, 6, 8])

In [82]:
arr2 = np.array([5,6,7,8])
print(arr1)
print(arr2)

[1 2 3 4 5]
[5 6 7 8]


In [90]:
arr1+arr2

array([ 6,  8, 10, 12])

In [68]:
arr1*arr2

array([ 5, 12, 21, 32])

In [76]:
arr2%arr1

array([0, 0, 1, 0])